version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      actions:
        patterns:
          - "*"
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      prod:
        patterns:
          - "*"
        exclude-patterns:
          - "ruff"
          - "pre-commit"
          - "poetry-plugin-export"
      dev:
        patterns:
          - "ruff"
          - "pre-commit"
          - "poetry-plugin-export"
