# fly.toml app configuration file generated for kusogaki-bot on 2024-10-26T09:54:51-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'kusogaki-bot'
primary_region = 'iad'

[build]
  dockerfile = 'Dockerfile'

[env]
  PORT = '8080'

[processes]
  app = 'python main.py'

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
