[build]
builder = "nixpacks"
buildCommand = "uv sync --no-dev --frozen"

[deploy]
startCommand = "uv run main.py"

[service]
memory = "1024M"
cpu = "1"

[env]
PORT = "8080"
DATABASE_URL = "${DATABASE_URL}"