[build]
builder = "nixpacks"
buildCommand = "pip install poetry && poetry install"

[deploy]
startCommand = "python main.py"

[service]
memory = "1024M"
cpu = "1"

[env]
PORT = "8080"
DATABASE_URL = "${DATABASE_URL}"