[format]
quote-style = "single"
line-ending = "auto"

[lint]
select = ["F", "E", "I"]
ignore = ["E501"]

[lint.isort]
known-first-party = ["kusogaki-bot"]
section-order = ["future", "standard-library", "third-party", "first-party", "local-folder"]
combine-as-imports = true

[lint.per-file-ignores]
"__init__.py" = ["F401"]
