name: Comment on PR for CI Failure

on:
  workflow_run:
    workflows: [ CI ]
    types: [ completed ]

permissions:
  pull-requests: write

jobs:
  comment-on-failure:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}
    steps:
      - name: Get PR Information
        uses: actions/github-script@v7
        id: get-pr
        with:
          script: |
            const response = await github.rest.repos.listPullRequestsAssociatedWithCommit({
              owner: context.repo.owner,
              repo: context.repo.repo,
              commit_sha: '${{ github.event.workflow_run.head_sha }}'
            });
            return response.data[0].number;

      - name: Create Comment
        uses: actions/github-script@v7
        with:
          script: |
            import { context } from '@actions/github';

            const prNumber = ${{ steps.get-pr.outputs.result }};
            const workflowUrl = '${{ github.event.workflow_run.html_url }}';
            const workflowName = context.eventName;

            const message = `❌ The job `${workflowName}` failed during the most recent run.

            Please check the [workflow run](${workflowUrl}) for more details.`;

            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: prNumber,
              body: message
            });